# -*- coding: utf-8 -*-
"""Ejercicios de práctica Fundamentos Python 03/09/2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uc_VzqAdbXbfyn9gDvearj_uUZRPvHxp

PROGRAMACIÓN PARA ANALÍTICA DE DATOS - MAESTRÍA

# Ejercicios practica Fundamentos Python 1

Profeso:  Elias Buitrago Bolivar

Estudiante: Jhon Freddy Alvino Lozano

# A. De la lógica a la decisión
Condiciones simples y estructuras if / else

1. Completa una decisión simple

Completa la condición para mostrar “Mayor de edad” cuando la variable edad sea mayor o
igual a 18.
"""

edad = 20
if edad >= 18:
   print("Mayor de edad")

"""2. Agrega la ruta alternativa

Completa la estructura para clasificar una temperatura como “Alta” si supera 30 grados y
“Normal” en caso contrario.
"""

temperatura = 30
if temperatura > 30:
    print("Alta")
else:
    print("Normal")

"""3. Predice la salida

Sin ejecutar, escribe exactamente qué imprimirá el programa.
"""

numero = 7
if numero % 2 == 0:
  print("Par")
else:
  print("Impar")

"""Sin ejecutar, escribe exactamente qué imprimirá el programa.

Respuesta: imprima impar ya que 7 no es divisible entre 2

# B. Múltiples condiciones

if / elif / else y orden de evaluación

4. Completa la clasificación

Agrega las dos expresiones faltantes para clasificar la nota.
"""

nota = 4.2
if nota >= 4.5:
  print("Excelente")
elif nota >= 4.0:
  print("Muy buen desempeño")
elif nota >= 3.0:
  print("Aprobado")
else:
  print("No aprobado")

"""5. Corrige el orden

El programa pretende mostrar “Excelente” para notas de 4.5 o más. Reescribe únicamente el
bloque condicional en el orden correcto.
"""

# Ejemplo mal evaludada
nota = 4.8
if nota >= 3.0:
  print("Aprobado")
elif nota >= 4.5:
  print("Excelente")

# Ejemplo correguida

nota = 4.5
if nota >= 4.5:
  print("Excelente")
elif nota >= 3.0:
  print("Aprobado")

"""Respuesta: Python evalúa de arriba hacia abajo y ejecuta la primera condición verdadera, por este motivo se debe estructurar desde el mayor intervalo hacia el menor dependiendo las diviciones

6. Traza la ejecución

Escribe la salida para valor = 12. Después indica cuál condición fue la primera verdadera.
"""

valor = 12
if valor < 5:
  print("A")
elif valor < 10:
  print("B")
elif valor < 15:
  print("C")
else:
  print("D")

"""Respuesta: La salida para el valor 12 es C ya que esta entre 10 a 14 en el intervalo, la condicion primera evaludada es < 5 ya que es prioriza el orden de las condiciones

# C. Operadores lógicos

Construye condiciones con and, or y not

7. Acceso con dos requisitos


Completa el operador lógico para permitir acceso solo cuando ambas variables sean
verdaderas.
"""

usuario_activo = True
tiene_permiso = True

if usuario_activo and tiene_permiso:
  print("Acceso permitido")
else:
  print("Acceso denegado")

"""8. Dos rutas válidas

Completa la condición: se permite continuar si existe correo válido o teléfono válido.
"""

Correo_valido = False
Telefono_valido = True

if Correo_valido or Telefono_valido:
  print("Continuar registro")
else:
  print("Faltan datos de contacto")

"""9. Usa negación

Completa la condición usando not para mostrar el mensaje solo si la cuenta NO está
bloqueada.
"""

cuenta_bloqueada = False
if not cuenta_bloqueada:
  print("Puede operar")

"""# D. Estructura repetitiva for

Recorrer rangos y controlar iteraciones

10. Recorre del 1 al 5

Completa range() para imprimir los valores 1, 2, 3, 4 y 5.
"""

for numero in range(1, 6):
  print(numero)

"""11. Recorre con paso

Completa range() para imprimir 2, 4, 6, 8 y 10.
"""

for numero in range(2, 11, 2):
  print(numero)

"""12. Predice el acumulado

Sin ejecutar, determina el valor final de suma.
"""

suma = 0
for i in range(1, 4):
  suma = suma + i
  print(suma)

"""Respuesta el valor que se imprimira es 6 (Explicación: 1+2+3 = 6), si fuera el rango entre (1,6) seria 1+2+3+4+5= 15

# E. Estructura repetitiva while

Repetir mientras una condición permanezca verdadera

13. Completa el contador

Completa la condición y la actualización para imprimir los números del 1 al 5.
"""

numero = 1
while numero <= 5:
  print(numero)
  numero = numero + 1

"""14. Encuentra el ciclo infinito


El siguiente programa nunca termina. Corrige solo la línea que falta dentro del ciclo.
"""

numero = 1
while numero <= 5:
  print(numero)
  numero += 1

"""Respuesta: Hace falta el codigo (numero +=1) para que el ciclo termine en 5

15. Control de intentos


Completa el ciclo para permitir máximo 3 intentos. No modifiques las líneas ya escritas.
"""

intentos = 0
while intentos < 3:
  clave = input("Ingrese la clave: ")
  intentos = intentos + 1
  print("Proceso finalizado")

"""# F. Elegir y combinar estructuras

for + if, while + condición y razonamiento sobre flujo

16. ¿for o while?

Escribe la estructura que elegirías en cada situación.

**Situación** **for / while** **texto en negrita**

Procesar exactamente 10 mediciones. **For**

Pedir una clave hasta que sea correcta. **while**

Imprimir los números del 1 al 20. **for**

Repetir un cálculo hasta que el error sea menor que 0.01. **while**

17. Combina for + if

Completa el programa para recorrer del 1 al 12 y mostrar únicamente los múltiplos de 3.
"""

for numero in range(1,13):
   if numero % 3 == 0:
     print(numero)

"""18. Predice antes de ejecutar

Escribe todas las líneas que producirá el programa.
"""

for numero in range(1, 8):
  if numero < 3:
    print(numero, "A")
  elif numero < 6:
    print(numero, "B")
  else:
    print(numero, "C")

"""Las lineas produccidas son:
1 A
2 A
3 B
4 B
5 B
6 C
7 C

# G. Del pseudocódigo a Python


Conserva la lógica y cambia la representación

19. Traduce una decisión


Completa el código Python para que represente exactamente el pseudocódigo mostrado.
"""

## PSEUDOCÓDIGO
## LEER nota
## SI nota >= 3.0 ENTONCES
##   ESCRIBIR "Aprobado"
## SI NO
##   ESCRIBIR "No aprobado"
## FIN SI
## PYTHON

nota = float(input("Nota: "))

if nota >= 3.0:
   print("Aprobado")
else:
   print("No aprobado")

"""20.  Traduce una repetición

Completa el programa Python equivalente al pseudocódigo.
"""

## PSEUDOCÓDIGO
## PARA i DESDE 1 HASTA 5 HACER
## ESCRIBIR i
## FIN PARA
## PYTHON

for i in range(1,6):
   print(i)

"""# Reto integrador

Combina entrada, repetición y decisión sin utilizar listas ni funciones

21. Clasificación de temperaturas


Completa todos los espacios. Antes de ejecutar, prueba mentalmente tu solución con los
valores: 15, 18, 22, 25 y 30.
"""

# El programa debe solicitar 5 temperaturas.
# Para cada una debe mostrar:
# "Baja" si t < 18
# "Normal" si 18 <= t <= 25
# "Alta" si t > 25

for i in range(5):
  t = float(input("Temperatura: "))
  if t < 18:
    print("Baja")
  elif 18 <= t <= 25:
    print("Normal")
  else:
    print("alta")

"""Autoevaluación rápida
1. ¿Puedo explicar cuándo usar if, elif y else?
2. ¿Puedo distinguir cuándo conviene for y cuándo while?
3. ¿Puedo identificar el riesgo de un ciclo infinito?
4. ¿Puedo traducir una decisión o repetición desde pseudocódigo a Python?

Respuesta:

1: Cuando utilizo if es porque voy a dar una condición al resultado es decir es un "si", cuando continuo con elif es porque voy a dar más condiciones después de la inicial y cuando utilizo else es cuando no se cumplen las condiciones es decir es el "no".

2: Utilizo for cuando identifico una variable el número de repeticiones que debo realizar o unos rangos definidos, y while cuando no tengo definido o contralo el rango y es a infinito y debo parar el código o implementar una condición donde se va a deteneer.

3: Si al momento de utilizar while empieza a correr hacia el infinito y no se va a detener en ningún momento hasta debemos darle parar al ejecutador si no continúa corriendo, adicional se puede poner una condición de salida y determinar en donde parar al momento de correrlo.

4: si es posible traducir una decisión desde el pseudocódigo a Python, cumple la misma función y no afecta la estructura o codigó.
"""